/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dip.lab2.student.solution1;

import javax.swing.*;

/**
 *
 * @author Matthew
 */
public class TIpCalulatorBox extends javax.swing.JFrame {
    
    private final String BILL_ERROR_MESSAGE = "Please enter the amount for the Bill";
    private ServiceQuality quality;

    /**
     * Creates new form TIpCalulatorBox
     */
    public TIpCalulatorBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodServiceQualityButtonGroup = new javax.swing.ButtonGroup();
        baggageQualityRadioButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        billTotalField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        foodServiceTipButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        baseBagPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numberOfBags = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        baggageTerribleQualityButton = new javax.swing.JRadioButton();
        baggagePoorQualityRadio = new javax.swing.JRadioButton();
        baggageFairQualityButton = new javax.swing.JRadioButton();
        baggageGoodQualityRadio = new javax.swing.JRadioButton();
        baggageExcellentQualityButton = new javax.swing.JRadioButton();
        baggageTipButtoln = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Bill Total");

        billTotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTotalFieldActionPerformed(evt);
            }
        });

        foodServiceQualityButtonGroup.add(jRadioButton1);
        jRadioButton1.setText("Terrible");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        foodServiceQualityButtonGroup.add(jRadioButton2);
        jRadioButton2.setText("Poor");

        foodServiceQualityButtonGroup.add(jRadioButton3);
        jRadioButton3.setText("Fair");

        foodServiceQualityButtonGroup.add(jRadioButton4);
        jRadioButton4.setText("Good");

        foodServiceQualityButtonGroup.add(jRadioButton5);
        jRadioButton5.setText("Excellent");

        jLabel1.setText("Service Quality");

        foodServiceTipButton.setText("Tip!");
        foodServiceTipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodServiceTipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel3)
                    .addComponent(billTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel1))
                .addContainerGap(96, Short.MAX_VALUE))
            .addComponent(foodServiceTipButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodServiceTipButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Food", jPanel1);

        jLabel2.setText("Base Tip per Bag");

        jLabel5.setText("# of Bags");

        jLabel6.setText("Service Quality");

        baggageQualityRadioButtonGroup.add(baggageTerribleQualityButton);
        baggageTerribleQualityButton.setText("Terrible");

        baggageQualityRadioButtonGroup.add(baggagePoorQualityRadio);
        baggagePoorQualityRadio.setText("Poor");

        baggageQualityRadioButtonGroup.add(baggageFairQualityButton);
        baggageFairQualityButton.setText("Fair");

        baggageQualityRadioButtonGroup.add(baggageGoodQualityRadio);
        baggageGoodQualityRadio.setText("Good");

        baggageQualityRadioButtonGroup.add(baggageExcellentQualityButton);
        baggageExcellentQualityButton.setText("Excellent");

        baggageTipButtoln.setText("Tip!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baggageExcellentQualityButton)
                    .addComponent(baggageGoodQualityRadio)
                    .addComponent(baggageFairQualityButton)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(baseBagPrice)
                        .addComponent(jLabel5)
                        .addComponent(numberOfBags))
                    .addComponent(jLabel6)
                    .addComponent(baggagePoorQualityRadio)
                    .addComponent(baggageTerribleQualityButton))
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(baggageTipButtoln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baseBagPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfBags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baggageTerribleQualityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baggagePoorQualityRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baggageFairQualityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baggageGoodQualityRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baggageExcellentQualityButton)
                .addGap(18, 18, 18)
                .addComponent(baggageTipButtoln)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Baggage", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billTotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTotalFieldActionPerformed
       
    }//GEN-LAST:event_billTotalFieldActionPerformed

    private void foodServiceTipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodServiceTipButtonActionPerformed

        try {
            double billTotalNum = Double.parseDouble(billTotalField.getText()) ;
        }
        catch (NullPointerException | NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, BILL_ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_foodServiceTipButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIpCalulatorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIpCalulatorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIpCalulatorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIpCalulatorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIpCalulatorBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton baggageExcellentQualityButton;
    private javax.swing.JRadioButton baggageFairQualityButton;
    private javax.swing.JRadioButton baggageGoodQualityRadio;
    private javax.swing.JRadioButton baggagePoorQualityRadio;
    private javax.swing.ButtonGroup baggageQualityRadioButtonGroup;
    private javax.swing.JRadioButton baggageTerribleQualityButton;
    private javax.swing.JButton baggageTipButtoln;
    private javax.swing.JTextField baseBagPrice;
    private javax.swing.JTextField billTotalField;
    private javax.swing.ButtonGroup foodServiceQualityButtonGroup;
    private javax.swing.JButton foodServiceTipButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField numberOfBags;
    // End of variables declaration//GEN-END:variables

}
